const express = require('express');
const courseController = require('./Controllers/coursesController').courseController;
const departmentController = require('./Controllers/departmentsController').departmentController;
const lecturerDepartmentController = require('./Controllers/lecturerDepartmentsController').lecturerDepartmentController;
const lecturerController = require('./Controllers/lecturersController').lecturerController;
const lectureController = require('./Controllers/lecturesController').lectureController;
const schoolController = require('./Controllers/schoolsController').schoolController;
const venueController = require('./Controllers/venuesController').venueController;
const views = require('./Views/views').views;

const router = express.Router();
router.post('/schools/add', schoolController.create);
router.post('/venues/add', venueController.create);
router.post('/courses/add', courseController.create);
router.post('/departments/add', departmentController.create);
router.post('/lecturer/add', lecturerController.create);
router.post('/lecture/add', lectureController.create);
router.get('/schools', async (request, response) => response.send(await views.find(schoolController, request.body)));
router.get('/venues', async (request, response) => response.send(await views.find(venueController, request.body)));
router.get('/courses', async (request, response) => response.send(await views.find(courseController, request.body)));
router.get('/departments', async (request, response) => response.send(await views.find(departmentController, request.body)));
router.get('/lecturer', async (request, response) => response.send(await views.find(lecturerController, request.body)));
router.get('/lecture', async (request, response) => response.send(await views.find(lectureController, request.body)));
module.exports = router;